// <auto-generated />
using System;
using Essensoft.Paylink.Alipay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newtonsoft.Json.Linq;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TerraMours.Framework.Infrastructure.Contracts.Commons;
using TerraMours.Framework.Infrastructure.EFCore;
using TerraMours_Gpt.Framework.Infrastructure.Contracts.Commons;

#nullable disable

namespace TerraMours_Gpt.Migrations
{
    [DbContext(typeof(FrameworkDbContext))]
    [Migration("20231215092731_updateRole")]
    partial class updateRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysMenuButtons", b =>
                {
                    b.Property<long>("MenuButtonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MenuButtonId"));

                    b.Property<string>("ButtonEnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ButtonShowName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<long>("RolesToMenuId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SysRolesToMenuRolesToMenuId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("MenuButtonId");

                    b.HasIndex("SysRolesToMenuRolesToMenuId");

                    b.ToTable("SysMenuButtons", (string)null);
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysMenus", b =>
                {
                    b.Property<long>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MenuId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExternalUrl")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsHome")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShow")
                        .HasColumnType("boolean");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MenuUrl")
                        .HasColumnType("text");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("MenuId");

                    b.ToTable("SysMenus", (string)null);
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysRole", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeptName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNewUser")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("RoleId");

                    b.ToTable("SysRole", (string)null);
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysRolesToMenu", b =>
                {
                    b.Property<long>("RolesToMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RolesToMenuId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("RolesToMenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("SysRolesToMenu", (string)null);
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal?>("Balance")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<string>("DeptId")
                        .HasColumnType("text");

                    b.Property<string>("DeptName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableLogin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpireTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HeadImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("ImageCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRegregisterPhone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<int?>("LoginFailCount")
                        .HasColumnType("integer");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.Property<string>("ShortPhone")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPhoneNum")
                        .HasColumnType("text");

                    b.Property<string>("UserTrueName")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.Property<DateTime?>("VipExpireTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("VipLevel")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("SysUser", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.ChatConversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConversationId"));

                    b.Property<string>("ConversationName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("ConversationId");

                    b.ToTable("ChatConversation", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.ChatRecord", b =>
                {
                    b.Property<long>("ChatRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatRecordId"));

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<long?>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int?>("ModelType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatRecordId");

                    b.ToTable("ChatRecord", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.CollectRecord", b =>
                {
                    b.Property<long>("CollectRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CollectRecordId"));

                    b.Property<bool?>("Collect")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Forward")
                        .HasColumnType("boolean");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<bool?>("Like")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<int?>("RecordType")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("CollectRecordId");

                    b.ToTable("CollectRecord", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.GptOptionsEntity", b =>
                {
                    b.Property<long>("GptOptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GptOptionsId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<ImagOptions>("ImagOptions")
                        .HasColumnType("jsonb");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<OpenAIOptions>("OpenAIOptions")
                        .HasColumnType("jsonb");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("GptOptionsId");

                    b.ToTable("GptOptions", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.ImageRecord", b =>
                {
                    b.Property<long>("ImageRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ImageRecordId"));

                    b.Property<int?>("CollectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int?>("ForwardCount")
                        .HasColumnType("integer");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<string>("ImagUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int?>("ModelType")
                        .HasColumnType("integer");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("PranslatePrompt")
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("ImageRecordId");

                    b.ToTable("ImageRecord", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.KeyOptions", b =>
                {
                    b.Property<long>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KeyId"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UnUsed")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Used")
                        .HasColumnType("numeric");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("KeyId");

                    b.ToTable("KeyOptions", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.PromptOptions", b =>
                {
                    b.Property<long>("PromptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PromptId"));

                    b.Property<string>("Act")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int?>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("PromptId");

                    b.ToTable("PromptOptions", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.Sensitive", b =>
                {
                    b.Property<long>("SensitiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SensitiveId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SensitiveId");

                    b.ToTable("Sensitive", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.GptModels.Verification", b =>
                {
                    b.Property<long>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VerificationId"));

                    b.Property<int?>("CodeType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string[]>("UsedUserIds")
                        .HasColumnType("text[]");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("VerificationId");

                    b.ToTable("Verification", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.PaymentModels.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool?>("IsVIP")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("TradeNo")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VipLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("VipTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.ProductModels.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.ProductModels.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool?>("IsVIP")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.Property<int?>("VipLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("VipTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.SystemModels.SysDictionary", b =>
                {
                    b.Property<long>("DictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DictionaryId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<JObject>("Dictionary")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("DictionaryId");

                    b.ToTable("SysDictionary", (string)null);
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.SystemModels.SysSettingsEntity", b =>
                {
                    b.Property<long>("SysSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SysSettingsId"));

                    b.Property<AlipayOptions>("Alipay")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreateID")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<Email>("Email")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<Initial>("Initial")
                        .HasColumnType("jsonb");

                    b.Property<string>("ModifierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifyID")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComputedColumnSql("xmin");

                    b.HasKey("SysSettingsId");

                    b.ToTable("SysSettings", (string)null);
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysMenuButtons", b =>
                {
                    b.HasOne("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysRolesToMenu", null)
                        .WithMany("SysMenuButtons")
                        .HasForeignKey("SysRolesToMenuRolesToMenuId");
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysRolesToMenu", b =>
                {
                    b.HasOne("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysRole", "SysRole")
                        .WithMany("RolesToMenus")
                        .HasForeignKey("RoleId");

                    b.Navigation("SysRole");
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.ProductModels.Product", b =>
                {
                    b.HasOne("TerraMours_Gpt.Framework.Infrastructure.Contracts.ProductModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysRole", b =>
                {
                    b.Navigation("RolesToMenus");
                });

            modelBuilder.Entity("TerraMours.Framework.Infrastructure.Contracts.SystemModels.SysRolesToMenu", b =>
                {
                    b.Navigation("SysMenuButtons");
                });

            modelBuilder.Entity("TerraMours_Gpt.Framework.Infrastructure.Contracts.ProductModels.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
